version: '3.7'
services:
  web:
    image: nginx:1.19.9
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/:/var/www/html

  app:
    build: ./
    volumes:
      - ./nginx/:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
